### ISSUE TITLE
No Documentation on How to Build/Compile the Manual Yourself

### ISSUE THREAD

**Issue by momer** [HaxeFoundation/HaxeManual#108]
It would be great if there was some info in the `README` on how to compile/build different versions of the manual yourself.

At the moment, I'm lost on how to build this via pdflatex. `pdflatex HaxeDoc.tex` spits up errors about a missing file, and I'm unsure if this is self-inflicted (via missing parameters in the command) or due to an issue with the repo. Simn on #haxe was able to compile an updated PDF using what I gather is a latex editor GUI, but documentation here is sorely needed for those looking to learn haxe, but are unable to build the manual without a little help.

Update - the errors I encountered seem to be due to a number of missing tex packages (framed, preprint, etc. etc. etc.). Should be noted somewhere in the docs that the build requires texlive-full; or mactex full; not the basic version.

**Comment by jonasmalacofilho** [comment]
Note: from the preprint collection of packages we only use fullpage.

**Comment by Simn** [comment]
This has been added, thanks @jonasmalacofilho!
