### ISSUE TITLE
Links to nonexistent pages cause 404

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#122]
http://haxe.org/manual/compiler-usage.html
If you click on the hyperlink "php" in the page for example, it redirects to "not found". Shouldnt such links be red?

**Comment by Simn** [comment]
They shouldn't be links in the first place.

**Comment by Simn** [comment]
Oh I see, it's a cross reference to an empty section. In that case I agree they should be red.

**Comment by markknol** [comment]
Can you fix that?

**Comment by Simn** [comment]
That's more of a haxe.org issue.

**Comment by jasononeil** [comment]
Is it?  The red, unclickable links are set to happen when the URL is "#".  In this case the generated markdown has a URL.  I guess I can do some pre-processing to see if the link is to a file that doesn't exist, but would it be easier to change the markdown output?

**Comment by Simn** [comment]
Oh, I thought you handled that. In that case I can take a look.
