### ISSUE TITLE
Target details c#

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#138]
It would be nice to have all target details covered with at least one or two pages. Who can write the c# details?

A basic target detail section should include:
- getting started, basic setup/configuration
- implementation details, like custom metatags/defines
- how to use libraries/external sources
- how to inject raw code

**Comment by nadako** [comment]
I could make some content for that, but I feel very uncomfortable (to put it mildly) with TeX tooling. If I make a text gist, could someone incorporate it into HaxeManual?

**Comment by markknol** [comment]
Yes I'm fine with that.

**Comment by nadako** [comment]
Started writing here https://gist.github.com/nadako/c225caf5fde5cee5dcd4, will continue tomorrow.

**Comment by nadako** [comment]
Moved what's done so far to the wiki, so @waneck and others can contribute :)

https://github.com/HaxeFoundation/HaxeManual/wiki/Haxe-C%23

**Comment by Simn** [comment]
@markknol: Please hold back on pull requests until I've dealt with https://github.com/Simn/HaxeManual/tree/repository-restructure because that's gonna change the entire repository structure and cause merge conflicts.

**Comment by markknol** [comment]
<img src="https://i.imgflip.com/k6az7.jpg" title="made at imgflip.com"/>

**Comment by Simn** [comment]
Should be done, let me know if you come across any problems.
