### ISSUE TITLE
Target details c++

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#139]
It would be nice to have all target details covered with at least one or two pages. Who can write the c++ details? 

A basic target detail section should include:
- getting started, basic setup/configuration
- implementation details, like custom metatags/defines
- how to use libraries/external sources
- how to inject raw code

**Comment by larsiusprime** [comment]
I am currently working on some stuff about CFFI. I should be able to eventually cover:

-- CFFI "legacy" (the old way)
-- CFFI Prime (the new way)
-- C++ externs

**Comment by ncannasse** [comment]
Nice! Once it's done @Hughsando can do a review. Basically we need to document all the C++ specific metadata and API which are used for FFI (you can get a list using `haxe --help-metas`)

**Comment by fullofcaffeine** [comment]
Excellent initiative. I've myself always been confused by the various CFFI
techniques.

Might be a stupid question, but what about Linc?
http://snowkit.org/2015/08/24/announcing-linc/

**Comment by larsiusprime** [comment]
@fullofcaffeine: Linc is an excellent example of the C++ externs method.
