### ISSUE TITLE
Metadata example broken

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#140]
See http://haxe.org/manual/lf-metadata.html
I tried the full example in a new project, but if gives this errors:

```
haxe  -debug --each -cp src -js C:/mark/projects/TestProject/bin/main.js -main Main -dce no

src/Main.hx:18: {}
src/Main.hx:19: characters 14-59 : Invalid field access : range
src/Main.hx:14: characters 8-14 : Called from
Aborted
Build halted with errors (haxe.exe).
```
Is this a haxe or manual issue?

**Comment by Simn** [comment]
That's caused by DCE. What are you doing with that --each there?

**Comment by markknol** [comment]
Ah it does work. Maybe a good one to mention in this example?

I dont know I just created a new flashdevelop Haxe Js project so that adds the `--each`?

**Comment by Simn** [comment]
Well it shouldn't cause any issues, so I don't know why it wasn't working for you. Either way it's not an issue for the manual.
