### ISSUE TITLE
 missing/broken asset (picture) links

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/HaxeManual#143]
See e.g. http://haxe.org/manual/type-system-resolution-order.html or the macro flow diagram.

**Comment by Simn** [comment]
I got confused by directories there but it should be fixed now. Waiting for the website to confirm.

**Comment by Simn** [comment]
@jasononeil: The images are there in the github markdown (https://github.com/HaxeFoundation/HaxeManual/blob/master/output/HaxeManual/website/type-system-resolution-order.md) but are missing on the website (http://haxe.org/manual/type-system-resolution-order.html). Do I have to update something else?

**Comment by jasononeil** [comment]
The paths in the markdown won't work in a different context:

src="../../../HaxeManual/assets/graphics/generated/type-system-resolution-order-diagram.png"

I had a workaround in place before, but it might have changed during this
commit
<https://github.com/HaxeFoundation/HaxeManual/commit/65e2227e94dd966fec031b4b326074b0dea51830>.
I'll fix it tonight and try set up some kind of automated test to make sure
this doesn't happen again.
