### ISSUE TITLE
Errors in Type-Building Page

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/HaxeManual#144]
1) The code example does not work.  Compiling fails with error: ```haxe.macro.ComplexType should be haxe.macro.VarAccess```

2) "It declares a new haxe.macro.expr.Field field using the funcName macro argument as field name. This field is a String variable with a default value "my default" (from the kind field) and is public and static (from the access field)." --- replace funcName with fieldName

**Comment by explorigin** [comment]
So #1 might be a bug in Haxe.  I've filed an issue here: https://github.com/HaxeFoundation/haxe/issues/4226

**Comment by Simn** [comment]
The code example does work as-is. I'll comment on the #haxe issue.
