### ISSUE TITLE
"Contribute to this page" link broken everywhere

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#145]
I think this is related to the new structure setup?

**Comment by Simn** [comment]
Yes but that's a haxe.org issue.

**Comment by jasononeil** [comment]
I'll take a look now.

**Comment by markknol** [comment]
Nice. Sorry, sometimes I don't exactly know what is part of what.

**Comment by Simn** [comment]
HaxeManual: content and everything related to how the markdown export looks

haxe.org: presentation on the website
