### ISSUE TITLE
Broken "Contribute to this page" links

### ISSUE THREAD

**Issue by bubblebenj** [HaxeFoundation/HaxeManual#147]
(Not sure this issue should be handled from here or haxe.org issue tracker)

As of today, all "Contribute to this page" links at the bottom the manual page leads to a 404 on github.
For instance : 
https://github.com/HaxeFoundation/HaxeManual/blob/master/12-target-details.tex#L1-1

**Comment by Simn** [comment]
#145

**Comment by cancerberoSgx** [comment]
@Simn @jasononeil  it seems this issue is happening again, I could open a new issue, but perhaps you just want  to use this one ? I don't know how to solve this..

**Comment by jasononeil** [comment]
It’s probably related to this update:

https://community.haxe.org/t/contributing-to-haxe-manual-is-easier-than-ever/1834

I’d open a new issue
