### ISSUE TITLE
Documentation for "=>" map literal syntax?

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/HaxeManual#157]
I couldn't find this anywhere

http://jasono.co/2013/04/16/the-new-map-syntax-in-haxe-3/

Thanks!

**Comment by jgranick** [comment]
Oh, found it here. VERY difficult to find :frowning:

http://haxe.org/manual/std-Map.html

**Comment by Gama11** [comment]
The term "map literal" should probably be mentioned on that page.

**Comment by jasononeil** [comment]
Agreed, we could mention it here too:

http://haxe.org/documentation/introduction/language-features.html

Pull requests welcome.

**Comment by markknol** [comment]
We might also put it here https://github.com/HaxeFoundation/HaxeManual/issues/161 as suggested by Jason, I think it should be under the title that is related to Map or something?

**Comment by Gama11** [comment]
>the title that is related to Map

Which one is that?

**Comment by markknol** [comment]
Its not there, I mean we should create a catchy paragraph about maps and mention this syntax also there.

**Comment by Gama11** [comment]
What else would you want to mention there? I would simply add a `Map Literals` section.

**Comment by markknol** [comment]
Ah okay, fair enough, would you mind to propose something here? :wink:
