### ISSUE TITLE
Feature request: images

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#160]
It would be nice to have some images, @Simn can you help me with the syntax? There are already graph-images in the manual but i see in a magical way they are generated (?).

While I know we should not add to much noise in the manual, I might want to add some screenshots. Also this would be a nice-to-already-have feature for the tut-sections. 

And it would also be nice to have the Haxe logo on the manual landing page, or something like the documentation introduction to spice it up a bit.    

Oh and is this an issue for the pdf/ebook?

**Comment by Simn** [comment]
@jonasmalacofilho: Some best practice advice for handling this in LaTeX would be appreciated!

**Comment by markknol** [comment]
Not needed anymore I guess

**Comment by jonasmalacofilho** [comment]
:flushed:

I remember starting to compile some recommendations, but somewhere along the way I must have ended up forgetting about it.  : /
