### ISSUE TITLE
Add some "Haxe only has expressions" code examples

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/HaxeManual#170]
See https://github.com/HaxeFoundation/HaxeManual/commit/5f7cb09c0e3803b6be1ed3626c85b030cfe809a1#commitcomment-11617946

**Comment by ncannasse** [comment]
Actually I feel that, while doing a great job at explaining the language spec, the Manual could be enriched with more examples.

Making sure that each concept is actually illustrated with some code examples would make sure that everything is actually well understood by the reader, as a double check.

Some people also prefer to read code that explanations, and only look at the spec if they want more details about how the code is working.

A few pages that I found could be examplified (or use more examples):

- http://haxe.org/manual/types-basic-types.html
- http://haxe.org/manual/types-overflow.html
- http://haxe.org/manual/types-enum-using.html
- http://haxe.org/manual/types-monomorph.html
- http://haxe.org/manual/types-dynamic.html

Maybe a complete review would be necessary

**Comment by Simn** [comment]
I cannot review my own text so you'll have to find someone else for that.

**Comment by Simn** [comment]
I don't really know what to do with this issue... so I'll just close it. We haxe code.haxe.org now for code examples.

**Comment by Gama11** [comment]
:+1:

There's actually one on this exact topic: http://code.haxe.org/category/principles/everything-is-an-expression.html
