### ISSUE TITLE
Coding convention

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/HaxeManual#184]
There are various coding conventions about Haxe. 

* http://nadako.tumblr.com/post/79958903007/on-my-haxe-coding-style
* http://haxeflixel.com/documentation/code-style/
* https://docs.google.com/document/d/1048lojT5vZDKi4Kx9j_gKakGSqMvdmuq7ppvGSpFaBM

I was wondering if the official Haxe manual could contains one of the coding conventions.

**Comment by Atry** [comment]
At least, for one who was contributing to the Haxe standard library.

**Comment by Simn** [comment]
I prefer to not deal with this because I think there are more important tasks. The coding conventions of the standard library can be easily discerned by looking at some code.
