### ISSUE TITLE
The manual sometimes is too up to date :D

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/HaxeManual#193]
This issue shows a haxe  user misusing haxe because the manual used a very recent feature without hinting for versions : 

https://github.com/HaxeFoundation/haxe/issues/4517

I sugggest when on feed the manual that the url of the page Or the page itself mentions at which version the feature is available.

Thanks.

**Comment by Simn** [comment]
Agreed, we should make sure to use `\since{3.2.0}` for these things.

**Comment by delahee** [comment]
@simn can you show me how it renders or some page using it ?

**Comment by Simn** [comment]
It's just a paragraph heading: http://haxe.org/manual/macro-reification-expression.html#since-haxe-3.1.0

**Comment by delahee** [comment]
Perfect.
