### ISSUE TITLE
Links on license page are messed up

### ISSUE THREAD

**Issue by 0joshuaolson1** [HaxeFoundation/HaxeManual#195]
See http://haxe.org/manual/introduction-license.html
But the manual tex and md versions look fine, so I'm not sure what to do here.

**Comment by markknol** [comment]
I think this is a haxe-markdown issue? https://github.com/dpeek/dox/issues/127

**Comment by markknol** [comment]
Done https://github.com/HaxeFoundation/HaxeManual/commit/2c3e11735bb983727a3a3c0e897d8106da88309d
