### ISSUE TITLE
`@:deprecated` meta isn't only for Java

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/HaxeManual#199]
Need fix description ([08-compiler-features.tex#L43](https://github.com/HaxeFoundation/HaxeManual/blob/master/HaxeManual/08-compiler-features.tex#L43)) about `@:deprecated` meta because it is not for Java only. It works fine for all Haxe-code at compile-time (and it must works in same way in future).
http://try.haxe.org/#539c9

**Comment by markknol** [comment]
Good point, if this is true, it should also be updated in common.ml for Haxe commandline help description https://github.com/HaxeFoundation/haxe/blob/183928ca5784c7ac90b6ffd36f5131c4e87d1c9a/common.ml#L396

**Comment by fzzr-** [comment]
It really "Has no effect on types compiled by Haxe". But _for all targest_ it throw warning about "Warning : Usage of this field is deprecated".

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/haxe/issues/4720
