### ISSUE TITLE
Built-in Compiler Defines specified for Flash

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/HaxeManual#218]
In the [12.2 Target Details/Flash](http://haxe.org/manual/target-flash.html) needed page with descriptions for all flash-specified defines such as `-D network-sandbox`, `-D swc`, `-D swf-use-doabc`,..

I'm not meaning copy-past from `$ haxe --help-defines` - there is a very concise descriptions in 1-2 lines. I think need more detailed descriptions like [here about `network-sandbox`](http://www.rocketshipgames.com/blogs/tjkopena/2013/01/opening-links-in-flash/) (of course without a lot of code).

**Comment by Simn** [comment]
We are not going to spend resources on updating flash-specific documentation.
