### ISSUE TITLE
Need more describe breaking cycle in cycle behaviour

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/HaxeManual#221]
[Page 5.20](http://haxe.org/manual/expression-break.html)

I mean need add  that examples and describe its for learners :) :

```haxe
public function a()
{
    function b()
    {
        while(true)
        {
            // breaks only current cycle
            break;
        }
    }
}
```

Also for `continue` & `return` for sub-cycles and anonymous & noname-  functions.

People often ask me this. And they wonder why it is not described in the manual.

**Comment by Simn** [comment]
I don't understand what you mean. Both `continue` and `break` abort the current innermost loop. I don't see what your code example is supposed to show either.

**Comment by markknol** [comment]
> The `break` keyword leaves the control flow of the innermost loop (`for` or `while`) it is declared in, stopping further iterations:

I think the confusion of most starters is `return` . This will make a function return something directly. I found myself also "misusing"  `return` to break out of loops.

@fzzr-  I don't think we need to document this in one page, they have both their own page and explanations now. Or maybe you have additional paragraphs that would make it more clear? I personally think if the starter has actually read the manual, it would not be that confused.

**Comment by fzzr-** [comment]
Sorry, I mean __all__ cases including interesting cases with unnamed blocks, cycles in generators,...

```haxe
trace("result: " + {
        var a = 42;
        trace('a="$a"');
        return;
        [a, a, a];
    });
```

```haxe
static function main() {
    function foo()
    {
        return [for(i in 0...42)
                {
                    if(i % 2 != 0)
                        // skip value because it's even
                        continue;

                    if(i == 10)
                        // break for-cycle because a value eq 10
                        // it isn't breaks all stack, only the current cycle
                        break;

                    trace('+"$i"');
                    // this block of iteration of for-cycle returns:
                    i;
                }];
    }
}
```

and about returns in blocks:

```haxe
function foo():Array<Int>
{
    return [for(i in 0...42)
            {
                if(i == 42)
                    // breaks for-in cycle, breaks & return from function:
                    return [0,0,0];

                i;
            }];
}
```
and about gen with cycle with switch :) :
```haxe
function foo(switcher:Null<Bool>):Array<Int>
{
    var i = 0;
    return [while(i < 100)
       {
            i++;
            switch(switcher)
            {
                // This is return from `foo` - current function:
                case true: return [42];

                // This is return from switch:
                case false: 42;
    
                // This is break will breaks array-generator with while-cycle:
    			default: break;
            };
        }];
}
trace("case true:\t " + foo(true).length);
trace("case false:\t" + foo(false).length);
trace("case null:\t " + foo(null).length);
```

I'll try to write some paragraphs with more __simple__ examples about `break`s, `continue`s and various `return`s as soon as possible. And I'll post it here. If you think what it needed of course, @Simn, @markknol.

**Comment by Simn** [comment]
I still don't get it. None of these are special cases, it all follows from control flow leaving only the innermost loop (for `break` and `continue`) or function (for `return`).

**Comment by Simn** [comment]
Closing because I don't see what we should do here.
