### ISSUE TITLE
try catch 

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#223]
This is something I always wondered. When a function throws an error like this:

```
throw "Invalid";
```

What is the type of the catch parameter?

I always cast my as Dynamic (`catch(e:Dynamic)`), but I feel I miss something.

http://haxe.org/manual/expression-try-catch.html

**Comment by Simn** [comment]
I'm not sure what you mean, if you throw a String then you can catch a String. Doesn't the page you linked make that pretty clear?

**Comment by markknol** [comment]
Well, yes and no. I never thought I could catch for a String, but I don't know why I thought this :smile:  For example, if I parse an invalid JSON, the documentation says: "an exception will be thrown". I cannot know (without looking) what kind of error will be trowed (or can I?) without looking in the implementation of course. 

I think an example with a string (a pretty common case) might explain it a bit more, what do you think?

**Comment by nadako** [comment]
I think when a doc says "an exception will be thrown", you should catch `Dynamic`, since the actual exception is most often target-dependent.

**Comment by markknol** [comment]
Ok so it wasnt that bad of an idea to use dynamic? Maybe we should put the type of the exception in the api documentation?

**Comment by ncannasse** [comment]
@markknol we can only tell for either platform-specific API (when they have exception types) or some crossplatform code we wrote (ex: haxe.io.Input/Output throwing haxe.io.Eof/Error). However we can't do it for native cross platform code because the exception type might be platform specific

**Comment by markknol** [comment]
Ah, so if I understand correctly, since Json (for example) can use a native implementation, the exception types are unknown?

In that case I understand how it now works, thanks for that!

I keep this open because I think it might be useful to have an extra pargraph with example and the information Nicolas just mentioned.

**Comment by Simn** [comment]
I don't think we have to add anything to that page. Having something about Json there would be totally random. If you think it's worthwhile, feel free to add something as a comment.
