### ISSUE TITLE
hxml spec

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/HaxeManual#224]
Need html format specification / description as a part (or sub-page) of ["7 Compiler Usage"](http://haxe.org/manual/compiler-usage.html).

**Comment by Simn** [comment]
The only hxml-specific arguments are --next and --each if I remember correctly.

**Comment by nadako** [comment]
Hmm, I thought you can use them without hxml, like `haxe -debug --each -js main.js --next -neko main.n`, am I wrong?

**Comment by Simn** [comment]
Uhm, that never really occurred to me, but if that works there's nothing hxml specific at all I guess.

**Comment by fzzr-** [comment]
* `--next` and `--each`
* including __sub-hxml__ and comment about resolving class-pathes and what "`cwd` for sub-hxml is inherit by main-hxml".

- - -

`--next` and `--each` isn't hxml-specific - it can be used simple in console `$ haxe -main Foo -cp src --each -js out.js -cmd node out.js --next ....`.

I think we have to describe all from `$ haxe -help` excluding defines and metas.

**Comment by markknol** [comment]
You can reference other hxml files in hxml files, you cannot do this commandline. It would be nice if we could pick some info from this useful post of @andyli, I always use this one as reference :+1: 
http://blog.onthewings.net/2013/03/04/hxml-tricks-every-haxe-user-should-know/

We should at least mention in the manual that the file format is a Haxe thingy.

**Comment by markknol** [comment]
We have it now https://haxe.org/manual/compiler-usage-hxml.html
