### ISSUE TITLE
Add link from 11.3 to 7.0 compiler usage or html-spec

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/HaxeManual#225]
Need link from ["11.3 extraParams.hxml"](http://haxe.org/manual/haxelib-extraParams.html) to description of hxml format. Now it ["7 Compiler Usage"](http://haxe.org/manual/compiler-usage.html) but additionally will be great if it will **spec** of `hxml`. Related issue: #224 .

**Comment by fzzr-** [comment]
Also same link needed from ["11.1 Using a Haxe library with the Haxe Compiler"](http://haxe.org/manual/haxelib-using-haxe.html). E.g.: "These commands are explained thoroughly in [Compiler Usage](#) and [__HXML__](#).".

**Comment by Simn** [comment]
I have removed haxelib documentation from this repository, so the issue is now obsolete.
