### ISSUE TITLE
Buildin defines description

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/HaxeManual#226]
1. Need describe all build-in compiler defines such as `haxe_ver` and its usage
 (e.g.: `#if haxe_ver > 3.1 ... #end`).
2. Need describe the behaviour when we use any library from Haxelib we automatically have new define with same name. For example we using `-lib foo` and can get true in `#if foo ... #end`.

I think it can be [there](https://github.com/HaxeFoundation/HaxeManual/blob/master/HaxeManual/07-compiler-usage.tex).

**Comment by Simn** [comment]
@markknol: Didn't you add that?

**Comment by markknol** [comment]
This one? http://haxe.org/manual/lf-condition-compilation-flags.html

**Comment by Simn** [comment]
Yeah!

That's in a bit of an awkward section. Should be somewhere under compiler usage as suggested.

**Comment by markknol** [comment]
`-D my_var=4` is compiler usage, `#if my_var` is a language feature?

**Comment by Simn** [comment]
Yes

Compiler defines are not strictly related to conditional compilation. While conditional compilation without defines doesn't make much sense, compiler defines have other effects as well. Conditional compilation should certainly link to the defines, but the defines section should be under compiler usage.

**Comment by fzzr-** [comment]
Also I mean buildin "autodefined" defines. For example

For Flash target:
* `flashX(X_X) = 1` e.g. `flash9`/`flash10`/`flash11_9` - automatically created by setted `-swf-version XX.X`. Generating starts from version passed to `-swf-version` and down to `flash9` and all will be equal `1`;

For all targets:
* `haxe2 = 1` for Haxe 2.X
* `haxe3 = 1` for Haxe 3.X
* `haxe_ver = X.X0X` e.g. `3.201` for Haxe v.3.2.1 and `3.1` for Haxe v.3.1.0;
* `true = 1` (yes!)
* `libname = X.X.X` for each used Haxelib-library (`-lib libname` / `-lib libname:X.X.X`);
* `sys = 1` for static targets excluding flash;
* `target-name = 1` e.g. for Javascript will be `js` / for C++ - `cpp`;
* `hxcpp_api_level = 321` (really for all targets);

Also for all targets:
* `macro = 1` in compile-time when macro executing;

**Comment by markknol** [comment]
if a `value = 1`, that mostly means it is true so it might be not needed to mention that it is "1".

Would it be an idea to add a new table after the almighty table? Something like this:

### auto defined flags
These values are automatically defined on each target by the Haxe compiler.

| flag | description |
|---|---|
| haxe-ver | The current Haxe version value. E.g. `3.201` for Haxe v.3.2.1 and `3.1` for Haxe v.3.1.0  |
| _libname_ | version number or each used Haxelib-library (`-lib libname` / `-lib libname:X.X.X`) |
| haxe3  | True if the Haxe version is 3.x  |
| haxe2  | True if the Haxe version is 2.x  |
| sys | True if running in static target context, excluding Flash.  |
| js | True if running in Javascript context |
| as3 | True if running in as3 context |
| swf | True if running in swf context |
| python | True if running in python context |
| csharp | True if running in csharp context |
| cpp  | True if running in cpp context  |
| php  | True if running in php context |
| macro | True if running in macro context |

_If a flag is defined, the value equals `1`_

**Comment by fzzr-** [comment]
1. Oh my stupid mistake: `sys` : Defined for all system platforms. (from `-help`)
2. `as3` : Defined when outputing flash9 as3 source code;
3. "`xxx` | True if running in xxx context" isn't totally understandably. Maybe "target is xxx" or "compiling/outputting (to) xxx" is more clearly?

+ `swc` | True if Flash & ext of output file is .swc (-swf lib.swc)

**Comment by markknol** [comment]
Those are good additions.

3. @simn do you have a better wording to describe the target defines?

**Comment by Simn** [comment]
I kinda like the context description. "True if compiling to target" works too though.

**Comment by fzzr-** [comment]
And one addition.

>_lib name_ | version number or each used Haxelib-library (`-lib libname` / `-lib libname:X.X.X`)

This isn't a number. It's a string and that fact is important because we can't work with this define as with `haxe-ver` for example:

```haxe
// used library "mylib" version = 0.4.6
#if (mylib > 0.4)
// never going to happen
#end

// always have to work with it as string:
#if (mylib == "0.4.6")
trace("YES");
#end
```
I think this fact should be strongly noted.

- - -

In this example
>version number or each used Haxelib-library (`-lib libname` / `-lib libname:X.X.X`)

I tried to visually highlight the identity of version (`X.X.X`) with the value of the define.

IMO, then it should look like this:
" _version_ string or each used Haxelib-library (`-lib libname` / `-lib libname:version`) "
