### ISSUE TITLE
Compiler features - Completion

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/HaxeManual#23]

**Comment by markknol** [comment]
Ok we have it here http://haxe.org/manual/cr-completion.html, fixed by https://github.com/HaxeFoundation/HaxeManual/pull/89

What about the BOM?

**Comment by Simn** [comment]
Indeed the BOM should at least be mentioned.

**Comment by markknol** [comment]
I have no idea how to describe this, can you help?

**Comment by Simn** [comment]
I guess we should just say that the reported offsets are byte position, not char position.
