### ISSUE TITLE
Boosting Current Version of Manual

### ISSUE THREAD

**Issue by indolering** [HaxeFoundation/HaxeManual#230]
When I search for Haxe content the top results is often from old.haxe.org.  This is occasionally useful as some content hasn't been ported over yet, however, the new stuff is usually better.

I would like to add direct links on the old wiki to the new one, both to help out users and improve the search rankings.  I can login but I don't see any UI indicating that I can edit the old wiki.

Can I get access to the old wiki?  If that's too much hassle, would anyone with access be interested in inserting those links?

**Comment by Simn** [comment]
I don't think we should mess about in the old wiki. The better approach is to just port the missing content to the new manual.

And no we can't do that automatically. The old wiki has a lot of useful information but it also has a lot of (outdated) nonsense.

**Comment by indolering** [comment]
> The better approach is to just port the missing content to the new manual.

But there are times when the new stuff does exist but the old stuff [still rises above it](https://www.google.ca/search?q=haxe+php).

**Comment by Simn** [comment]
@Merelleya: Can we "help" google with that somehow?

**Comment by Merelleya** [comment]
Usually it takes time, especially if the old content was very good/detailed. We could either tell google not to crawl old.haxe.org anymore or we could also try putting canonical tags on the old pages, although, seeing as the content is similar but not exactly the same, google could still ignore that.

**Comment by markknol** [comment]
We can help google, by putting all content from old.haxe into the manual and close it forever. But that takes time :stuck_out_tongue_winking_eye: 

I believe there is already some forwarding, this is done here: https://github.com/HaxeFoundation/haxe.org/blob/master/www/website-content/oldwiki.csv

**Comment by indolering** [comment]
> Can we "help" google with that somehow?

That's why I suggested linking to the new pages : )

**Comment by Simn** [comment]
I think this will sort itself out over time, especially once all still relevant content has been ported.
