### ISSUE TITLE
Usage examples for compiler metatags

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/HaxeManual#232]
I've recently stumbled upon the `extern` reserved keyword and the `@:extern` metatags. The usage of `extern` is documented here: http://haxe.org/manual/lf-externs.html and is all clear, but it's all too easy to confuse with the metatag since they are called the same.

Would it be possible to provide usage examples for all metatags? Most of the descriptions here: http://haxe.org/manual/cr-metadata.html, are too abstract and can't be easily understood.

It would also be nice to mention the `@:extern` metatag in the documentation for `extern`, since they seem related.

**Comment by Simn** [comment]
This issue is too wide. There are a lot of metatags and providing usage examples for each of these would take a very long time. We can look into improving things after dealing with https://github.com/HaxeFoundation/haxe/issues/3959, but for now I'll go ahead and close here.
