### ISSUE TITLE
Document anonymous structures as a shorter alternative way to define typedefs

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/HaxeManual#237]
I was wondering what was the practical difference here:

`typedef Foo = { x : Datatype, ?y: Datatype }` vs `typedef Bar = { var x : Datatype, @:optional var y : Datatype }``

Turns out they behave the same. Nice, good to have more options, but this specific aspect (that you can mix and match those two syntaxes and that they fulfil the same goal) **is not documented**. I think it should be documented in the "Typedef" section, here: http://haxe.org/manual/type-system-typedef.html, as a note.

If you guys are ok with it, I can add it there.

**Comment by nadako** [comment]
As I said, this is not related to `typedef` and the alternative structure notation is actually documented under the "Anonymous structure" section: http://haxe.org/manual/types-structure-class-notation.html

However @Simn, why we have **Optional fields** paragraph in the `typedef` section and not in the page I linked above? I can see this adds confusion.

**Comment by fullofcaffeine** [comment]
Sorry but I have to disagree. It's is related to `typedef`, since we have agreed that it can be considered as an alternate syntax to create them.

**Comment by nadako** [comment]
I don't understand. Both syntaxes you mentioned relate only to anonymous structure definition. Typedef has nothing to do with structures, it allows to create an alias for **any** type, e.g. `typedef Id = String`, and anonymous structure is just one kind of *type*.

**Comment by nadako** [comment]
You can use anon structure syntax without a typedef at all, e.g.

```haxe
var some:{a:Int,?b:String};
function f(v:{var a:Int; @:optional var b:String});
```

**Comment by fullofcaffeine** [comment]
Oh, I get it now. Yeah, you're right.

**Comment by fullofcaffeine** [comment]
Closing this, thanks for taking the time to elaborate @nadako , I now understand and see that it's indeed documented.

**Comment by nadako** [comment]
I'll re-open because I think this is still relevant:

> However @Simn, why we have Optional fields paragraph in the typedef section and not in the page I linked above? I can see this adds confusion.

**Comment by Simn** [comment]
Yes that should be moved. I thought I did that a long time ago, but apparently not.

**Comment by Simn** [comment]
I've moved it now!
