### ISSUE TITLE
Ast diagram

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#240]
https://github.com/nickmain/haxe-macros/tree/master/cheatsheets

Is this something we can use? Looks very neat.

**Comment by Simn** [comment]
That looks neat, I wonder how it is generated.

Not sure if it's suitable for the manual, it has a very different visual style and has to be viewed at full size.

**Comment by markknol** [comment]
I think it is manually created using OmniGraffle. 

@nickmain I'm pinging you, because I think your graph is great. Would you think it is much work to make it fit into the current visual style? 
It would be great if it could be smaller/more vertical?

 I mean something like this: 

![example graph](http://haxe.org/manual/macro-compilation-role.png)

**Comment by Simn** [comment]
I like the visual style and size of the graph, that shouldn't be changed just to fit into the manual. It's better to simply link it.

**Comment by nickmain** [comment]
Please link to it, or fork - whatever meets your needs. Unfortunately, I don't have enough discretionary time to make a custom version.

The goal was to be information dense and complete - so I don't think it fits the format of a tutorial or manual.

**Comment by Simn** [comment]
Closing here because I don't see much we can do. It's nice to have the resource, but I don't think it has to be in the manual.
