### ISSUE TITLE
Document escape sequence issues

### ISSUE THREAD

**Issue by indolering** [HaxeFoundation/HaxeManual#244]
The C target [confounds the use of `\`](https://github.com/HaxeFoundation/haxe/issues/4930) in regular expressions (`~/invalidLiteral\./`) and strings (`"urlEncoded\/path"`).  This is not mentioned in the regex documentation.  Not sure how/where to document the string issue....

**Comment by ncannasse** [comment]
I'm not sure I understand the issue. Could you show some code that should work and fails?

**Comment by indolering** [comment]
@ncannasse `~/invalidLiteral\./` should work fine, but the compiler catches it an spits out an error because of how c handles backslash characters.

Trying to fix the problem by adding escapes (`trace(cidr.match("192.168.1.0\\/24"))`) doesn't work on targets like JavaScript.  Not sure how to document the problem....

**Comment by Simn** [comment]
> @ncannasse ~/invalidLiteral\./ should work fine, but the compiler catches it an spits out an error because of how c handles backslash characters.

That's not true, it works perfectly fine in a regex literal. The problem was that you tried escaping like that in a string literal and \. is not a supported escape sequence there.

Having said that I still don't know what exactly I'm supposed to document here.
