### ISSUE TITLE
Duplicate haxelib documentation

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/HaxeManual#245]
Currently, https://github.com/HaxeFoundation/HaxeManual/blob/master/HaxeManual/11-haxelib.tex file duplicates info in https://github.com/HaxeFoundation/haxelib/tree/development/www/documentation-files (and the latter is more up-to-date). I propose removing it from HaxeManual, and add a link to haxelib documentation instead, since managing docs in haxelib repo is easier and more straightforward.

We may want to keep the old urls, so this'll need some redirection settings.

Related #43

**Comment by Simn** [comment]
Agreed
