### ISSUE TITLE
Document @:impl

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#246]
I saw it here
http://haxe.org/manual/types-abstract-selective-functions.html

But not here
http://haxe.org/manual/cr-metadata.html 
nor in the `haxe --help-metas`

**Comment by Simn** [comment]
I don't want to document this because it's an implementation detail. The section on selective functions should be removed.

**Comment by Simn** [comment]
Let's leave it open to remember to deal with the selective functions.

**Comment by Simn** [comment]
Covered by https://github.com/HaxeFoundation/HaxeManual/issues/227
