### ISSUE TITLE
Extending Class<T> with static extensions

### ISSUE THREAD

**Issue by ashes999** [HaxeFoundation/HaxeManual#258]
I added [this PR](https://github.com/HaxeFoundation/code-cookbook/pull/39) ([raw markdown](https://raw.githubusercontent.com/HaxeFoundation/code-cookbook/100519cce961d8ca16da5f57681be4c291b8d163/assets/content/cookbook/Other/adding-static-methods-to-existing-classes.md)) to the Haxe Code Cookbook, which explains how to create a `Math.randomBetween(a, b)` method by creating a static extension with `Class<Math>` as the first argument.

I originally wanted to add this to the [static extensions section](https://github.com/HaxeFoundation/HaxeManual/blob/master/HaxeManual/06-language-features.tex#L96) but I don't know TeX.

Could you please replicate my content over?

**Comment by ashes999** [comment]
@markknol as requested, I've created an issue

**Comment by Simn** [comment]
I don't think it has to be in the manual. It's not a special case but a combination of "features", so the cookbook is a better place for it.

**Comment by markknol** [comment]
You are right @Simn, is it needed to describe the usage of `Class` somewhere in the type system section?

**Comment by Simn** [comment]
It is mentioned here: http://haxe.org/manual/types-class-instance.html

**Comment by markknol** [comment]
Ah good! (I didnt see it before :open_mouth: )
