### ISSUE TITLE
Conditional haxe_ver checking

### ISSUE THREAD

**Issue by eliasku** [HaxeFoundation/HaxeManual#260]
Example how to check built-in `haxe-ver` define. It would be great! 
I've expected it here: https://haxe.org/manual/lf-condition-compilation.html
I'm talking about:

```
#if (haxe_ver >= "3.3")
```

or

```
#if (haxe_ver >= 3.3)
```

Now discovered just by reading Std, or third-party libraries, but I think it's essential information for new users, especially that's been used a lot.

And don't understand the difference on checking the string or float

**Comment by markknol** [comment]
Hi, It is mentioned in the list of all flags here https://haxe.org/manual/compiler-usage-flags.html

**Comment by eliasku** [comment]
@markknol I need to see description how I shoud compare these strings "x.x.x". Are there any specific rules for strings / int / float comparison? Also need to be clear in documentation about what exactly `haxe_ver` represent. Just "X.X", or "X.X.X". Is there tag or something expected or not.

**Comment by markknol** [comment]
The rule for string comparisons (because a version is a string) is alphabetical. So "AAA" is smaller than "BBB", and "1.0" is smaller than "2.0".  

Since I believe there is no actual number comparison,  "1.0" is smaller than "1.0.0.0" too ;)

**Comment by ibilon** [comment]
https://github.com/HaxeFoundation/haxe/issues/2908#issuecomment-41010548

We really should document that.
