### ISSUE TITLE
missing documentation about $ vars in trace 

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/HaxeManual#267]
https://haxe.org/manual/lf-trace-log.html

I was look how to escape a $ in a trace ... 
But I don't even see it mentioned in the manual

I use this a lot which is an awesome feature
```
var foo = 'bar';
trace ('foo-$foo');
```

etc

**Comment by Simn** [comment]
That is not trace-specific and documented at https://haxe.org/manual/lf-string-interpolation.html

**Comment by MatthijsKamstra** [comment]
That might be the case, and I don't want to be a smart ass here.

But I am **highly** invested in Haxe and I could not find it.

And the documentation is for people like me (I hope).
So perhaps a section "related subjects?"

But the link is exactly what I was looking for, just couldn't find it
So my problem is fixed, thx
