### ISSUE TITLE
Document anonymous structure inheritance/type spread operator

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/HaxeManual#269]
I saw this syntax in [`Type.hx`](https://github.com/HaxeFoundation/haxe/blob/de17354927f84d46320b57bf69e3d469e2352211/std/haxe/macro/Type.hx#L396) and had been wondering how to do the same thing in my own code:

```haxe
typedef ClassType = {> BaseType,
```

I don’t see anything glaringly obvious about this in [Anonymous Structure](https://haxe.org/manual/types-anonymous-structure.html). Is this something I’m allowed to do in my own code and what are the rules for it? If it really is as self explanatory as it appears, I could try writing a snippet about it. But I don’t actually know what to call it ;-).

**Comment by Simn** [comment]
https://haxe.org/manual/type-system-extensions.html

But yes, that's in the wrong place (should be under https://haxe.org/manual/types-anonymous-structure.html) and not easy to find if you don't know exactly what it is.

**Comment by binki** [comment]
Ah, that’s helpful. I didn’t realize that the class var syntax for declaring anonymous structs could be used to denote readonly properties on them either. That could be really powerful for some amount of immutable-like stuff.

If I find time and no one beats me to it, my plan would be to move that to be a subsection of Anonymous Types and also link to it from the parent Anonymous Types topic directly with some text like “Class-like inheritance can be done using Anonymous Structure Extensions”.
