### ISSUE TITLE
dictionary.html "Page not found"

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/HaxeManual#271]
On https://haxe.org/manual/expression-var.html, `identifier` links to https://haxe.org/manual/dictionary.html#define-identifier, which is a dead link ("Page not found, sorry.").

**Comment by Krilivye** [comment]
Same on https://haxe.org/manual/types-class-instance.html  `rules for type identifiers` links to https://haxe.org/manual/dictionary.html#define-identifier

**Comment by markknol** [comment]
Will be there in next deploy
