### ISSUE TITLE
var initialisation 

### ISSUE THREAD

**Issue by championchap** [HaxeFoundation/HaxeManual#274]
I [opened an issue](https://github.com/HaxeFoundation/haxe/issues/6011) about variable initialisation on the main Haxe repo last night thinking I may have found a bug, but it seems that it was just a misunderstanding due to poorly worded documentation. 

This page suggests to me that `var a, b = 2;` should set a AND b to 2, but I have since learned that this is not the case. 

https://haxe.org/manual/expression-var.html

**Comment by Simn** [comment]
Looks like @nadako already addressed this.
