### ISSUE TITLE
Dead links in Section 2, Types.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/HaxeManual#275]
Referring page: http://haxe.org/manual/types.html
At the bottom of the page, in the tips section, the two links for "type parameters" and "function" type go to error pages.
```
<blockquote class="define">
  <h5>Define: Compound Type</h5>
  <p>A compound type is a type which has sub-types. This includes any type with 
    <a href="type-system-type-parameters.md">type parameters</a> and the 
    <a href="types-function.md">function</a> type.
  </p>
</blockquote>
```

**Comment by Simn** [comment]
@ibilon: Any idea why the HTML conversion misses these? It links to .md instead of .html.

**Comment by ibilon** [comment]
I think it's because the link are in a "Define" block, I'll check.

**Comment by markknol** [comment]
Good job!
