### ISSUE TITLE
Description of the compiler service "@diagnostics"

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/HaxeManual#280]

**Comment by chipshort** [comment]
Same for the other new compiler services, like `@statistics`

**Comment by Simn** [comment]
We aren't going to add documentation for these modes. What we'll do instead is provide this documentation as part of our new json-based API. We already have that for the modes we "ported": https://github.com/vshaxe/haxe-languageserver/blob/master/src/haxeLanguageServer/protocol/Display.hx

Once diagnostics and statistics mode are ported as well, they will become part of that API documentation.
