### ISSUE TITLE
Error "Couldn't parse manual file"

### ISSUE THREAD

**Issue by fantostisch** [HaxeFoundation/HaxeManual#289]
The manual file is not parsed on the following pages:
https://haxe.org/manual/types-nullability.html
https://haxe.org/manual/types-class-instance.html
https://haxe.org/manual/types-enum-instance.html

![screenshot from 2017-06-05 21-23-55](https://cloud.githubusercontent.com/assets/3309700/26799311/51f38de2-4a35-11e7-99f0-58f4380b87a0.png)

**Comment by markknol** [comment]
This is fixed now. Travis used Haxe development version which unfortunately failed. 
https://github.com/HaxeFoundation/haxe.org/commit/484e786263153b8763684ef9a194ea0df60bea91
