### ISSUE TITLE
Compiler usage - add addClassPath

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#296]
`--macro addClassPath('test')` is useful to mention too.

**Comment by markknol** [comment]
No, maybe it is not that useful to mention, since it doesn't do what I thought.

**Comment by Gama11** [comment]
What did you think it does?

**Comment by markknol** [comment]
I thought it included a folder, but im not sure if thats the case. isn't this the same as doing `-cp test` ?

**Comment by Gama11** [comment]
> isn't this the same as doing -cp test

Yep.

**Comment by markknol** [comment]
Ok cool. That's why it is not useful to document and correct why I closed it.
