### ISSUE TITLE
Metadata example does not work on try.haxe

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/HaxeManual#297]
First example from this page does not work on try.haxe because of `-dce full`
https://haxe.org/manual/lf-metadata.html
https://try.haxe.org/#F3A54
```
14:24:01:001   [object Object]
14:24:01:002   Uncaught TypeError: Cannot read property 'range' of undefined,https://try.haxe.org/program/50d9f/run?r=0.23607475419273038,line:17
```

**Comment by markknol** [comment]
I think adding a `@:keep` in the example will do, with a (code)comment of why that is needed. That will keep it independent of the compiler configuration.
