### ISSUE TITLE
Import page does not discuss import.hx.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/HaxeManual#302]
https://haxe.org/manual/type-system-import.html

Should have a conversation (starting with a rewrite of nadako's blog post? https://haxe.org/blog/importhx-intro/) about how to use import.hx and how it interacts with other imports and usings.

**Comment by Simn** [comment]
The general message should be that import.hx acts as if its contents are placed at the top of each module. I just have to figure out where and how to communicate that.
