### ISSUE TITLE
Allow anonymous user-contributed notes on every page

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/HaxeManual#309]
When I started with PHP ( many years ago... ), one of the great parts about it was that you could read other people's clarifications, warnings and solutions for common usages of a command.

E.g. you go to research [`substr`](http://php.net/manual/en/function.substr.php) and the top comment actually warns you to use `mb_substr` instead, or the top comment for `microtime()` of course [describes how to trace execution time by only using one var](http://php.net/manual/en/function.microtime.php#111107), etc.

The important part is that the notes : 
- can be submitted quickly and without having to sign up anywhere
- are `<pre></pre>` formatted
- and syntax highlighted from the get-go

No fanciness, just quick notes dropped off when you need them.

**Comment by markknol** [comment]
I like the idea of adding comments, we could use Discuss like [the blog](https://haxe.org/blog/abstracting-primitives/#disqus_thread).
The possible downside is that the comments can go out of date and someone should be responsible to manage comments. 

@ncannasse @simn @nadako What do you think?

**Comment by mastef** [comment]
I don't like Disqus on man pages for 2 reasons : 
- By default it's not good to submit code related ( syntax-formatted ) questions / comments in it
- Forcing somebody to sign up for an account loses a vast majority of drive-by comments/questions

Usually when I see Disqus on man pages there are no comments.

**Comment by ncannasse** [comment]
I think having something to post comments is good. And we need someone to sign up and proper accounts because of anti spam measures, so I think Disqus is a good choice.

**Comment by ibilon** [comment]
Was added by @markknol

**Comment by mastef** [comment]
With github comments - great! Thanks for that!
