### ISSUE TITLE
Quick URL shortcuts/forwarders to common topics

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/HaxeManual#310]
Another example that made it easier/faster to learn php was that I just needed to type in [`php.net/date`](http://php.net/date) to be auto-forwarded to `http://php.net/manual/en/function.date.php`.

If you misspelled a function/topic, it would give you suggestions [`php.net/dat`](http://php.net/dat)

**Comment by markknol** [comment]
We don't actually have information about misspelled pages, in theory it can be done by creating custom redirections.
https://github.com/HaxeFoundation/haxe.org/blob/staging/src/generators/Redirections.hx

**Comment by mastef** [comment]
Do you have analytics about the most common visited haxe manual pages somewhere?

**Comment by mastef** [comment]
I was mainly talking about api.haxe.org behaviour - there seems to be some basic error handling configured, as https://api.haxe.org/Date shows https://api.haxe.org/Date.html correctly ( but https://api.haxe.org/date ) doesn't.

Would be nice if https://haxe.org/date would forward to https://api.haxe.org/Date

**Comment by Gama11** [comment]
I mean.. why not just use the search box? :)

**Comment by mastef** [comment]
This issue is about convenience

**Comment by mastef** [comment]
Actually a quick fix could be also to add to the 404.html the js results from the search page

So instead of seeing a non-descript
https://haxe.org/date
You'd see a : 
https://haxe.org/search/#gsc.tab=0&gsc.q=date&gsc.sort=

**Comment by ibilon** [comment]
I'm really against url rewriting for 404 errors.
But adding search result "you might have been looking for this:" could be done.

**Comment by mastef** [comment]
Definitely not suggesting url-rewrites to 404 errors. The search results would have to be shown in the 404 error page.

The url rewrites would be custom-rewrites for the most common accessed api pages/terms. E.g. 
`haxe.org/date` -> `api.haxe.org/Date.html`
`haxe.org/string` -> `api.haxe.org/String.html`

Also about adding url-rewrites that catch capitalisation errors
`https://api.haxe.org/String` -> `https://api.haxe.org/String.html` ( currently works )
`https://api.haxe.org/string` -> `https://api.haxe.org/String.html` ( currently doesn't work )

**Comment by markknol** [comment]
This is a nice idea but should be done on server, dox is only for generating the pages. You could try opening issue at https://github.com/HaxeFoundation/api.haxe.org but I don't see this happening soon. Thats the reason I'll close this issue for now.

**Comment by mastef** [comment]
@markknol isn't the error html page generated by dox?

**Comment by mastef** [comment]
I've submitted a PR to dox as first step https://github.com/HaxeFoundation/dox/pull/236
