### ISSUE TITLE
On line reference manual non aligned to source code.

### ISSUE THREAD

**Issue by vincentb1** [HaxeFoundation/HaxeManual#311]
I am referring to this page: [Construction of generic type parameters](https://haxe.org/manual/type-system-generic-type-parameter-construction.html)

The example in the on-line manual has this piece of sample code:
``` haxe
typedef Constructible = {
  public function new(s:String):Void;
}
```

while the PDF built from source has this:
``` haxe
import haxe . Constraints ;
```

One more difference in the sample code is as follows, on line:
``` haxe
  static function make<T:Constructible>():T {
```

while the PDF built from source has this:
``` haxe
static function make<T: Constructible<String ->Void>>():T {
```

**Comment by Simn** [comment]
This will be fixed by regenerating the pdf.
