### ISSUE TITLE
Makefile does not work for me, and hash sign makes source code xelatex compilation error.

### ISSUE THREAD

**Issue by vincentb1** [HaxeFoundation/HaxeManual#312]
Attached is  a patch file to fix the Makefile so that PDF compilation will occur, and also to fix some problem in the source code with the hash sign in URL's.

[hashpatch.diff.zip](https://github.com/HaxeFoundation/HaxeManual/files/1586166/hashpatch.diff.zip)

Please note that I have not tested the makefile target `dist-clean`, however I edited it, because it had the same inconsistency as the rest of the makefile.

**Comment by markknol** [comment]
Would it be possible to provide a PR too?

**Comment by vincentb1** [comment]
I will do that by end of today&hellip;

**Comment by vincentb1** [comment]
Done: [PR#318](https://github.com/HaxeFoundation/HaxeManual/pull/318)

**Comment by Simn** [comment]
#318 was merged, so I assume this is fixed.
