### ISSUE TITLE
« §7.2 Global Compiler Flag » table wrongly typset in PDF output

### ISSUE THREAD

**Issue by vincentb1** [HaxeFoundation/HaxeManual#313]
A longtable or supertabular, possible with page geometry change to landscape layout is needed.

The table spills out of the page.

**Comment by vincentb1** [comment]
Attached is a patch of what I mean (please note that it fixes also on hash sign, as pointed out in issue #312). It is based on the supertabular package.

[supertabular.diff.zip](https://github.com/HaxeFoundation/HaxeManual/files/1588106/supertabular.diff.zip)

I have tried this patch with PDF compilation, and it works fine, however, when compiling to epub (with `make md`) I get the following compilation error: 
```
Uncaught exception - 07-compiler-usage.tex:75: characters 8735-8745: No match: TCustomCommand(tablehead)
Error: Command failed with error 1
make: *** [Makefile:7: md] Error 1
```
So, probably you will have some homework before you can take this fix on board.

**Comment by vincentb1** [comment]
One more point: the same big table problem occurs in « 8.1 Built-in Compiler Metadata » table.

**Comment by markknol** [comment]
About the PDF generation; I don't know how up to date it is actually (I never check it thoroughly, and mostly skip generation 😳) 

@simn hopefully knows about this. But if you feel adventurous, please help on this.

**Comment by Simn** [comment]
I have applied your fix and it works. However, I currently don't have plans to update our markdown generator to support it. I have pushed the change to this branch and generated the new PDF from it: https://github.com/HaxeFoundation/HaxeManual/tree/pdf

Thank you!
