### ISSUE TITLE
Document @signature display mode 

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#317]
https://haxe.org/manual/cr-completion.html

From: https://github.com/HaxeFoundation/haxe/issues/6804 by @SlavaRa

**Comment by SlavaRa** [comment]
Any progress? @nadako?

**Comment by nadako** [comment]
Not really. I didn't want to document it to be honest, because I still believe we'll come up with some new compiler interaction API for 4.x, but I guess the what we currently have isn't going anywhere anytime soon, so I guess we could document it indeed...

**Comment by SlavaRa** [comment]
And what about those who do not use the new compiler?

**Comment by SlavaRa** [comment]
Bump

**Comment by Simn** [comment]
See comment in #280.
