### ISSUE TITLE
Haxe/C Hashtag

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/HaxeManual#328]
Hashtag # is not rendered
https://haxe.org/manual/target-cs-getting-started.html
https://github.com/HaxeFoundation/HaxeManual/blob/master/HaxeManual/12-target-details.tex#L890

**Comment by ibilon** [comment]
https://github.com/dpeek/haxe-markdown issue

```haxe
trace(Markdown.markdownToHtml("# C#"));
```
gives `M.hx:5: <h1>C</h1>`.

**Comment by ibilon** [comment]
Comes from https://github.com/dpeek/haxe-markdown/blob/master/src/markdown/BlockParser.hx#L80
