### ISSUE TITLE
Unnecessary page title disambiguation in navigation

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/HaxeManual#331]
See here for instance:

https://haxe.org/manual/std-regex-map.html

The titles for the parent nodes are repeated in the navigation, which ends up looking rather strange:

![](https://i.imgur.com/crHAea8.png)

According to @ibilon this happens due to disambiguation, as there are multiple pages with those titles (Map and Implementation Details).

**Comment by markknol** [comment]
@ibilon if you have time, can you take a look at this ?
Just using Map should be enough?

**Comment by ibilon** [comment]
Fixed by https://github.com/HaxeFoundation/haxe.org/commit/e8501563f17be68dd8406dfd84b6c1b1d095d75a
