### ISSUE TITLE
Single-quote strings aren't highlighted properly

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/HaxeManual#332]
![](https://i.imgur.com/Z4w4WWK.png)

From https://haxe.org/manual/lf-string-interpolation.html.

**Comment by markknol** [comment]
I fixed this recently for the code cookbook highlighter, so same changes should be applied here too https://github.com/HaxeFoundation/code-cookbook/commit/02c2b78b2e7c3994e11fb0ec43eed4398fe4a50f

**Comment by markknol** [comment]
Good one. maybe I should make it a haxelib.

**Comment by ibilon** [comment]
Couldn't we use https://github.com/vshaxe/haxe-TmLanguage like github does?

**Comment by Gama11** [comment]
I think GitHub renders it server-side - you can't really run TmLanguage grammars in the browser (too slow + JS regexes are too limited). So you would have to precprocess it on Travis or something. However, that might not be too hard to pull off with linguists API?

https://github.com/github/linguist#usage

**Comment by Gama11** [comment]
Nice. Linguist might even support HXML soon: https://github.com/github/linguist/pull/4092 ;)

**Comment by ibilon** [comment]
> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules as listed here.

So no need for linguist, I'm trying to find a tool/library that can use the grammar and export html or expose the tokens but so far nothing.

**Comment by Gama11** [comment]
Hm... https://github.com/github/linguist/issues/1984

**Comment by ibilon** [comment]
See HaxeFoundation/haxe.org#315.
