### ISSUE TITLE
Include HXCPP docs

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/HaxeManual#339]
@hughsando has recently written some great docs for HXCPP here:

https://github.com/HaxeFoundation/hxcpp/tree/master/docs

Unfortunately, these are not very easy to find / google. I think it would make sense to include them in the [C++ section of the Haxe Manual](https://haxe.org/manual/target-cpp.html)? They use markdown, but I think the LaTeX sources of the Haxe Manual are converted to that anyway? So it'd probably not be too hard to include this in the build step somehow. Or is it a straight LaTeX -> HTML conversion?

Right now, the manual has very little information compared to the docs in the HXCPP repo, just compare the docs for defines for the two for instance:

- https://github.com/HaxeFoundation/hxcpp/blob/master/docs/build_xml/Defines.md
- https://haxe.org/manual/target-cpp-defines.html

The Haxe Manual version is just a dump of defines without any additional info on them, while the HXCPP docs have some very valuable additional details.

@pchertok Maybe this is something you'd be interested to look into?

**Comment by pchertok** [comment]
Yes I can take care of this.

**Comment by Simn** [comment]
Well, he didn't...

@ibilon: Any smart ideas on how we could handle this? The documentation source should remain in markdown, but still look like it's part of the rest.

**Comment by ibilon** [comment]
Do we want those as part of the latex/pdf output or just the website? The latter would be a lot easier.

If we do a table of content for them they should be easy enough to put into the generated markdown.
I'll look into it.

**Comment by Simn** [comment]
Just the website is fine.

**Comment by ibilon** [comment]
A first version is on staging, but will need some more tweaking, a better doc and changing slightly the md files from hxcpp so that the formatting works.

**Comment by Simn** [comment]
Thanks a lot for looking into this!
