### ISSUE TITLE
Target macro ?

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/HaxeManual#348]
According to this page https://api.haxe.org/sys/ssl/Socket.html , Socket class is available on target macro, but here https://haxe.org/manual/target-details.html   , macro is not mention.  What target is macro ? 
In Haxe unit test is available "test macro" and all changes are test against macro.

**Comment by markknol** [comment]
Sorry for the late delay but the "macro target" is what is used in macros (https://haxe.org/manual/macro.html) but also is used by the  interpreter when compiling with  `--interp` (https://haxe.org/manual/compiler-usage.html)
