### ISSUE TITLE
match function absent from the manual

### ISSUE THREAD

**Issue by elnabo** [HaxeFoundation/HaxeManual#351]
I didn't find any information about the `match` function in the manual.

```haxe
enum A { B; C;}
class Main {
    public static function main () {
        var a = B;
        trace(a.match(C));
    }
}
```

**Comment by markknol** [comment]
I think it could be added here https://haxe.org/manual/lf-pattern-matching-enums.html

**Comment by elnabo** [comment]
It might requires to rewrite the example. As speaking of the function `match` and the variable `match` may be confusing.

**Comment by markknol** [comment]
Also should be mentioned you can use a `_` in the match function
```haxe
enum A { 
B(i:Int); 
C(s:String);
}
class Main {
    public static function main () {
        var a = B;
        trace(a.match(C(_));
    }
}
```

**Comment by elnabo** [comment]
You could also do
```haxe
var a = C("great");
var b = "great";
trace(a.match(C(b))); // true
```

Using the variable `b` withtout capture.

I guess doing a new page for it with all the specific no guard, no capture, ... might be simpler and better. This way the other example can stay as they are.

**Comment by markknol** [comment]
Also relevant https://api.haxe.org/haxe/EnumValueTools.html#match

**Comment by elnabo** [comment]
The doc might be used but the page shouldn't be linked.
https://try.haxe.org/#e0B8F
