### ISSUE TITLE
Operator precedence

### ISSUE THREAD

**Issue by neillrobson** [HaxeFoundation/HaxeManual#372]
On the following line of documentation:

https://github.com/HaxeFoundation/HaxeManual/blob/7f11818fabd74a0c6773c068314588412e96a3c1/HaxeManual/02-types.tex#L142

    % have lower precedence than * and / whereas in C these three have the same

I may be misunderstanding the definition of the word "precedence" here. My understanding is that lower precedence means that the operator would be executed _later_ in the sequence of expression resolution. In [this issue](https://github.com/HaxeFoundation/haxe/issues/7070) on the main Haxe repository, it seems as though modulo has a higher precedence according to this definition. Indeed, modulo is listed above multiply/divide in the table which is stated to be ordered in descending precedence. 

The same could be said for the bitwise operators mentioned two lines below (they are _higher_, not _lower_ precedence than comparison operators).

Am I misunderstanding the documentation? If not, I will go ahead and submit a PR fixing this issue.

**Comment by Simn** [comment]
Yes that seems backwards...
