### ISSUE TITLE
convert the manual to markdown

### ISSUE THREAD

**Issue by uvtc** [HaxeFoundation/HaxeManual#374]
I'm working on converting the manual from LaTeX to markdown but have some questions and will probably need some help after fixing up some broken links.

Please let me know if you want me to continue the conversion. (I'm hoping I'm not biting off more than I can chew, as my schedule is about to get very busy again...)

I originally wrote up my rationale for this. If you'd like, I can post it, but it's probably not anything you haven't already heard. I'd like to help contribute to the docs, but don't want to work with LaTeX. I think the conversion will jump-start a lot of additions to the manual.

Last I heard you'd like to leave the code samples as separate files. Personally, I don't think this is worth it, because it's way more convenient for writers to have the snippets right there in front of you while writing documentation. The code samples don't seem long enough to warrant needing to be tested. Just my 2 cents. Let me know if they should stay separate.

I don't know much LaTeX. I'm using Pandoc to do the final conversion from LaTeX to markdown, but first need to convert the `\newcommands` in haxe.cls to raw LaTeX so Pandoc can convert them correctly (well, as close as possible --- they'll probably need to be patched up a bit afterwards).

My plan is to make two passes with a global search/replace script. One pass before pandoc touches the file, and again after to fix up the `\haxe{assets/Foo.hx}` into something Pandoc can work with (via a filter), if that's the direction we want to go in.

Right now I'm converting things like `\type{foo}` to `\texttt{foo}` (along with `\expr` and `\ic`).

Before Pandoc touches the tex, should

    \Fullref{foo}

be converted to

    {\nameref{foo} \Cref{foo}}

(that is, remove the parentheses from what's in the newcommand in haxe.cls)?

I'll apply the answer to `\tref` as well.

Will remove `\flag` and `\todo`.

Thanks!

**Comment by uvtc** [comment]
Hm. I'm seeing

    {this and that \ref{this-and-that}

throughout the docs. That should translate to

    [this and that](path/to/somewhere#this-and-that)

correct?

**Comment by uvtc** [comment]
(Previous comment deleted: I can just check the currently-rendered docs for that.)

**Comment by uvtc** [comment]
Just noticed that I can't find the rest of the c++ portion of the target-details file.

Going back to look around, I just noticed that a bunch of changes landed while I was converting files to md.

**Comment by uvtc** [comment]
I got this far: http://www.unexpected-vortices.com/temp/manual/doc/index.html

**Comment by jonasmalacofilho** [comment]
What are you changing in comparison to what's currently generated to [`/output`](https://github.com/HaxeFoundation/HaxeManual/tree/master/output/HaxeManual/website) (with the custom tool in [`/convert`](https://github.com/HaxeFoundation/HaxeManual#generating-markdown))?

**Comment by uvtc** [comment]
I didn't think to look there, though probably should have. I'd assumed that Pandoc would get me good markdown right from the LaTeX source, and it did well.

I didn't finish the last two chapters (types and type-system), so hadn't prepared a PR, but you can see the markdown source via the link I posted of any rendered file by scrolling down and clicking "Pandoc-Markdown source for this page".

The main differences appear to be:

* In the files I generated, many (most?) of the intra-document links are half-broken and would need to be fixed. Many just contain the id, but not the page they point to.

* The md files I made are nested like this:

~~~
.
├── class-fields
│   ├── access-modifier.md
│   ├── method.md
│   ├── overview.md
│   ├── property.md
│   ├── toc.conf
│   └── variable.md
├── compiler-features
│   ├── built-in-compiler-metadata.md
│   ├── compiler-services.md
│   ├── dead-code-elimination.md
│   ├── resources.md
│   ├── runtime-type-information.md
│   ├── static-analyzer.md
│   └── toc.conf
├── compiler-usage
│   ├── global-compiler-flags.md
│   ├── hxml.md
│   ├── synopsis.md
│   └── toc.conf
├── _copyright
├── debugging
│   ├── debugging-in-javascript.md
│   ├── logging-and-trace.md
│   ├── position-info-param.md
│   ├── source-maps.md
│   ├── toc.conf
│   └── tracing-types.md
├── expressions
│   ├── array-access.md
│   ├── array-declaration.md
│   ├── blocks.md
│   ├── cast.md
│   ├── constants.md
│   ├── field-access.md
│   ├── flow-control.md
│   ├── function-call.md
│   ├── local-functions.md
│   ├── new.md
│   ├── object-declaration.md
│   ├── operators.md
│   ├── overview.md
│   ├── toc.conf
│   ├── type-check.md
│   └── var.md
├── haxelib.md
├── index.md
├── introduction
│   ├── about-this-document.md
│   ├── hello-world.md
│   ├── history.md
│   ├── toc.conf
│   └── what-is-haxe.md
├── language-features
│   ├── access-control.md
│   ├── array-comprehension.md
│   ├── conditional-compilation.md
│   ├── externs.md
│   ├── function-bindings.md
│   ├── inline-constructors.md
│   ├── iterators.md
│   ├── map-comprehension.md
│   ├── metadata.md
│   ├── overview.md
│   ├── pattern-matching.md
│   ├── static-extension.md
│   ├── string-interpolation.md
│   └── toc.conf
├── macros
│   ├── arguments.md
│   ├── initialization-macros.md
│   ├── limitations.md
│   ├── macro-context.md
│   ├── overview.md
│   ├── reification.md
│   ├── toc.conf
│   ├── tools.md
│   └── type-building.md
├── standard-library
│   ├── data-structures.md
│   ├── input-output.md
│   ├── json.md
│   ├── lambda.md
│   ├── math.md
│   ├── reflection.md
│   ├── regular-expressions.md
│   ├── remoting.md
│   ├── serialization.md
│   ├── string.md
│   ├── sys.md
│   ├── template.md
│   ├── toc.conf
│   ├── unit-testing.md
│   └── xml.md
├── target-details
│   ├── cppia.md
│   ├── cpp.md
│   ├── cs.md
│   ├── flash.md
│   ├── java.md
│   ├── javascript.md
│   ├── lua.md
│   ├── php.md
│   └── toc.conf
├── toc.conf
├── types
│   └── 02-types.tex
└── type-system
    └── 03-type-system.tex
~~~

whereas the generated ones are all in one directory, and broken up differently, and into more files.

* The ones I made still have the links to the .hx sample code files. In /output, the sample code files have already been embedded.

* Also, I hand-crafted the tables in mine, so they're easier on the eyes, and possibly easier to work on. Compare:

https://raw.githubusercontent.com/HaxeFoundation/HaxeManual/master/output/HaxeManual/website/cr-metadata.md

http://www.unexpected-vortices.com/temp/manual/doc/compiler-features/built-in-compiler-metadata.md

* For this work, I didn't make any changes to the actual doc content, just the formatting from LaTeX to md.

***

I haven't looked carefully to see other differences in the md source I got vs what's in /output (but what's in /output looks pretty nice). I'm actually pretty confused here. I'd assumed that there was a desire to move to markdown as the doc source format, but now I see we already have approximately that in the /output directory. And it looks like substantial work has gone into the conversion here from LaTeX to markdown.

**Comment by jonasmalacofilho** [comment]
Thanks for pointing out the differences.

> The ones I made still have the links to the .hx sample code files. In /output, the sample code files have already been embedded.

I think the separation is indeed necessary (if Markdown is to be adopted).

> Also, I hand-crafted the tables in mine, so they're easier on the eyes, and possibly easier to work on

Your tables do look a lot better.  But wouldn't this make them harder to maintain, as every change would (likely) require fixing the indentation?

> I'm actually pretty confused here. I'd assumed that there was a desire to move to markdown as the doc source format, but now I see we already have approximately that in the /output directory. And it looks like substantial work has gone into the conversion here from LaTeX to markdown.

There has been some discussion about this...  I don't know what's the position of the Haxe Foundation.

_paging @Simn_

My argument (against it) at the time was that a structured format allows more features and checks than what can be _sanely_ done with Markdown.[1]

> And it looks like substantial work has gone into the conversion here from LaTeX to markdown.

At the very least, `convert.n` already knows how parse all constructs used in the LaTeX sources.  You could try adapting it to include the improvements you're talking about.

---

[1] I was also working on a new format in-between LaTeX and Markdown for a [large engineering manual](https://github.com/ITDP/the-online-brt-planning-guide).  Though that project hasn't really lived up to my expectations.

**Comment by Simn** [comment]
I still feel like working on 200 single .md files is terrible, but at this point I'm willing to give up the .tex so people stop crying about it.

**Comment by uvtc** [comment]
> Your tables do look a lot better. But wouldn't this make them harder to maintain, as every change would (likely) require fixing the indentation?

In theory, you'd think so. But in practice, I find that looking at a nicely laid out table encourages editing, whereas a big block appears more daunting to the writer.

That's the thing about markdown. Although it's designed *first* for the purpose of looking good in plain text, and in fact does require slightly more effort to actually edit than some other similar formats, it still wins. I think it's because writers just like their source format to look pretty. :)

> My argument (against it) at the time was that a structured format allows more features and checks than what can be sanely done with Markdown.

Speaking for myself, I know that if I spend a lot of time learning how a given language/library feature works, at the end: (1) it's late, (2) I'm tired, (3) I'm inclined to document my learning, and uniquely positioned to do so (since I've just been staring at the manual and trying things for a while and see what I wish the manual had told me). At this point, if I open up the manual doc source and it's in LaTeX, docbook, groff, POD, reST, or really any format which I've got to spend time (re-)familiarizing myself with, I'm more likely to skip it.

So, yes, markdown is less structured, but in the end more people contribute to it, and errors are usually not too serious, and are easy to spot and fix.

> At the very least, convert.n already knows how parse all constructs used in the LaTeX sources. You could try adapting it to include the improvements you're talking about.

Alas, at this point, I poured all my free time into that conversion work last night and due to work responsibilities have nearly no time left until maybe next weekend. I'm still learning haxe, and don't yet understand how convert.n does what it does. Pandoc is a black box for me to convert other formats to markdown, and then convert markdown to html. :)

**Comment by uvtc** [comment]
> I  still feel like working on 200 single .md files is terrible,

I agree. I count 255 md files in that output directory. Many are very small. It would be a hassle to dig around to find the one you want (especially if the links in the html manually don't directly correspond to a like-named md file).

An additional issue I would have editing those is just seeing the overall big picture and figuring out where given (or new) docs would need to go. Personally, although the nav pane in the current rendered docs automatically expands/contracts depending upon where you are, I'd prefer to have a full unchanging table of contents so I can fully see where I am wrt the rest of the manual.

In my conversion I divided it up into 83 files, but had a handful more to go. They're organized under subdirs, are fairly medium-sized, and seem pretty easy to navigate around.

> but at  this point I'm willing to give up the .tex so people stop crying about  it.

I'm hoping you're not talking about me here. I worked on converting files and asked questions regarding if it was the right way to go. If anything, I mistakenly assumed you likely wanted to convert from LaTeX to markdown --- sorry about that.

Incidentally though, my guess is that for every one potential doc contributor who complains about the manual being in LaTeX, there's ten more who simply move on, don't contribute, and never say anything.

**Comment by jonasmalacofilho** [comment]
@uvtc,

I don't think there is a problem with the source format.  Writing content to a technical manual is hard because of the delicate balance that needs to be found between the learning curve of any potential reader and the preciseness of the content.

Though I suppose we might get a few more contributions with Markdown, due to the perception that TeX is the barrier.  Even if in most cases it's not really necessary to locally build the TeX document, or even run `convert.n` (we have CI to check things and we plain text still looks like text in TeX).

---

@Simn, John wrote:

> Personally, although the nav pane in the current rendered docs automatically expands/contracts depending upon where you are, I'd prefer to have a full unchanging table of contents so I can fully see where I am wrt the rest of the manual.

This is something I had many discussions when building the manual I linked before.  I think that both groups of users – those that prefer to see only part of the hierarchy at a time, and those that prefer to see everything at once – are more of less equally sized.

I'll see if I can come up with a good solution for this, hopefully something a bit better than a "expand all" button that makes the side bar unusable.  (In that project we actually had three separate ways to view the hierarchy).

**Comment by uvtc** [comment]
> I'll see if I can come up with a good solution for this, hopefully something a bit better than a "expand all" button that makes the side bar unusable. (In that project we actually had three separate ways to view the hierarchy).

Maybe just a separate, static, full table-of-contents page? Readers who don't want that could ignore it, and readers who want it could use it as their main launch page and read every page directly from it if they wanted to. I like the idea because looking it at gives me context of where I am in the manual, as well as an overall view of everything else that's in there.

**Comment by uvtc** [comment]
Ok, looks like there isn't enough interest in going down this particular avenue, so I'm going to close this issue.

If you decide down the road to make the jump and use the generated md files in /output as your doc source, I think it would also help to merge some of them together in the process to make editing easier.
