### ISSUE TITLE
String literals

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/HaxeManual#380]
The string literals page is severely lacking in details.

 - [ ] escape sequences (`\n` and similar for special low ASCII values, `\x`, `\u`)
 - [ ] link to string interpolation
 - [ ] UTF-8 details (`Utf8` in the standard library, which targets should actually use it, etc)
 - [ ] target-specific encoding details (#177 but updated)

**Comment by Gama11** [comment]
Inline markup needs to be documented somewhere too. That might deserve its own page, but should at least be linked to from here.
