### ISSUE TITLE
Extraneous indentation on some pages

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/HaxeManual#388]
Many pages have have unnecessary indentation / whitespace in code snippets:

https://haxe.org/manual/lf-pattern-matching-variable-capture.html
https://haxe.org/manual/lf-pattern-matching-enums.html
https://haxe.org/manual/lf-pattern-matching-guards.html
etc

**Comment by Aurel300** [comment]
These all use the `\haxe` command to extract a range of lines from a particular file:

https://github.com/HaxeFoundation/HaxeManual/blob/master/HaxeManual/06-language-features.tex#L392

Possible solutions:

 - add an optional argument to `\haxe` to adjust the indentation level on an excerpt - some LaTeX programming necessary, but shouldn't be too bad?
 - separate the files into individual snippets - the individual files still have to compile, so they would have to include `class Main` etc, which would clutter the code examples a lot

**Comment by Gama11** [comment]
>the individual files still have to compile, so they would have to include class Main

CI at least supports expression-level snippets:

https://github.com/HaxeFoundation/HaxeManual/blob/master/tests/RunTravis.hx#L109

**Comment by Aurel300** [comment]
Oh, you're right. However the pattern matching examples still need the `enum Tree` :)

**Comment by Gama11** [comment]
https://github.com/HaxeFoundation/HaxeManual/blob/master/tests/RunTravis.hx#L94 ;)

**Comment by Gama11** [comment]
I guess I basically wrote some kind of build system when I set up the CI here... :D
