### ISSUE TITLE
utteranc.es misconfiguration

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/HaxeManual#390]
It seems utteranc.es is configured to assign comments to articles based on their title only. This should be changed to the full URL slug (the `\label` in LaTeX), because some (sub)sections have the same title:

 - https://haxe.org/manual/lf-static-extension.html
 - https://haxe.org/manual/macro-limitations-static-extension.html

The comment on those actually belongs to the macro one, not the language feature one.

**Comment by Gama11** [comment]
Oh, now that comment finally makes sense to me...
