### ISSUE TITLE
Define: breaks if all text is quoted

### ISSUE THREAD

**Issue by cancerberoSgx** [HaxeFoundation/HaxeManual#417]
It seems if all the text following `##### Define: ` is quoted then it won't be shown, examples failing: 

In https://raw.githubusercontent.com/HaxeFoundation/HaxeManual/master/content/02-types.md

```
> ##### Define: `Class<T>`
> ##### Define: `Enum<T>`
> ##### Define: `Null<T>`
```

This happens in other places of this file and in other files so it seems is a generation error. 

Pages with the issue:

https://haxe.org/manual/types-enum-instance.html
https://haxe.org/manual/types-class-instance.html
etc

Thanks

**Comment by Aurel300** [comment]
This was fixed during the conversion.
