### ISSUE TITLE
add more details about rational behind some surprising design choices

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/HaxeManual#42]
Hi,
it would be great to explain in manual the rationnal behind design choices that are unexpected compared to java / C# / actionscript.
For example in: 04-class-field.tex chapter it would be usefull to explain why theres is no "real" private notion and only protected one is used.
Same need to explain the constructor function name new, even if its more easy to understand.
And also same need for for loops that only use the foreach paradigm and no more the classical for(i=0, i<length, i++). by the way the for loop chapter should also explain how to use haxe for loop to do a for i loop with for(i in 0..length) 

thanks

**Comment by Simn** [comment]
See https://github.com/HaxeFoundation/Project-Management/issues/47
