### ISSUE TITLE
Automatically deploy manual

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/HaxeManual#424]
Currently the workflow for deploying manual changes is:

 - update HaxeManual
 - update the `manual` submodule in haxe.org staging branch
 - pull staging into master
 - wait for CI to deploy master

As per a discussion on Slack some time back, could we instead:

 - have 2 branches in HaxeManual, master and staging, just like in haxe.org
 - master should always be behind or at the same commit as staging (no direct push)
 - pushing to HaxeManual staging will cause the CI to deploy the manual into haxe.org staging (online, not GitHub)
 - same for HaxeManual master and haxe.org master

Is this possible with the Travis APIs?

cc @andyli

**Comment by andyli** [comment]
That sounds more complex than what we currently have. What is the problem we're trying to solve here?

**Comment by Aurel300** [comment]
It's a more complex setup, but simpler from the user's perspective (just push HaxeManual and you'll see it online in a second). I would just like to separate the updates of HaxeManual from haxe.org, which may have unrelated changes.

**Comment by andyli** [comment]
What about I just make it auto-update the submodule in haxe.org's staging branch?

I don't what to introduce another staging/prod branch in more repo because I think our branch usage is a mess. We have a "development" branch in haxe, but its actually more like a master branch and its actual "master" branch being useless. We have "staging" branch in haxe.org, but again I think it should be named "master" and have another "production" branch.

**Comment by Aurel300** [comment]
I don't think the 2-branch model is bad, it's just bad naming. But anyway, auto-updating the submodule in haxe.org/staging would be quite helpful.

**Comment by Aurel300** [comment]
After some more thought on this I think there is a better solution. I would say that haxe.org should not include HaxeManual as a submodule, because that implies it is locked to a particular commit. As far as I can tell, there should never be a reason for the master branch of HaxeManual to ever not be the one that we want on the website.

Instead, we could simply clone the manual in the haxe.org CI. This would also make it a tiny bit more practical to work on the manual – I end up symlinking the manual directory to a local clone of the HaxeManual repository anyway, so that I can do regular git operation on it.
