### ISSUE TITLE
Backticks are messed up

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/HaxeManual#440]
https://haxe.org/manual/target-cpp-build_xml-TopLevel.html

**Comment by Aurel300** [comment]
I think I fixed this back in https://github.com/HaxeFoundation/HaxeManual/commit/aee5cdf3bfbffafa2aa22a4ec78255f4cbfa7f03

We just really need to update the manual submodule in haxe.org …

**Comment by RealyUniqueName** [comment]
Done
