### ISSUE TITLE
change to Haxe 4 compiler command line switch / option style

### ISSUE THREAD

**Issue by uvtc** [HaxeFoundation/HaxeManual#442]
Now that v4 is out, change the manual to use the new syntax? See these commits:

https://github.com/HaxeFoundation/HaxeManual/commit/f35425459fa1c65e35bec1bc9456505da3e39474

https://github.com/HaxeFoundation/HaxeManual/commit/a67addd7c10d784e1da837ef365598b9a89f3174

**Comment by uvtc** [comment]
Sorry, forgot to ping @Aurel300 

My git-fu is not strong enough to find those and submit a PR reverting them.

**Comment by Aurel300** [comment]
Closed with 547dbd2ce1dd575d5a2af8d7831c5d77a5e4bf06.

Sorry I didn't get back to this earlier.
