### ISSUE TITLE
Documentation for UnsafeStringMap

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/HaxeManual#456]
Currently the documentation is avaible: https://api.haxe.org/haxe/ds/UnsafeStringMap.html
But not the class if you click on View Sources: https://github.com/HaxeFoundation/haxe/blob/4.0.5/std/haxe/ds/UnsafeStringMap.hx

It should point to: https://github.com/HaxeFoundation/haxe/blob/development/std/flash/_std/haxe/ds/UnsafeStringMap.hx ?

**Comment by RealyUniqueName** [comment]
Looks like a dox issue.

**Comment by lublak** [comment]
Yes of course. Sry for the wrong repo.
