### ISSUE TITLE
There is no entry explaining `comments` in Haxe Manual

### ISSUE THREAD

**Issue by mingodad** [HaxeFoundation/HaxeManual#478]
Starting to dive in Haxe and needing to find how `documentation comments` are writing in Haxe I could not find anything about `comments syntax` in the Haxe Manual, probably an entry about comments should exists I know that it uses the same comments as Javascript/C/C++/Java but for new comers it's not clear, specially the `documentation comments`.

**Comment by markknol** [comment]
It's a bit hidden but there is documentation here https://github.com/HaxeFoundation/dox/wiki/How-to-document-Haxe-code
