### ISSUE TITLE
Document @:expose and other metadata

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/HaxeManual#57]
http://old.haxe.org/manual/haxe3?version=15672#modern-mode

**Comment by markknol** [comment]
We now have this http://haxe.org/manual/target-javascript-metatags.html does this need further explanation?

**Comment by Simn** [comment]
I think `@:expose` in particular needs an example. There's also `-D shallow-expose`.

**Comment by nadako** [comment]
It's also not only about `window` object, but node.js `exports` too.
