### ISSUE TITLE
Neko overflow

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/HaxeManual#83]
https://github.com/HaxeFoundation/haxe/issues/3552

**Comment by Simn** [comment]
I don't really know what to write here.

**Comment by ncannasse** [comment]
Neko have both int and float runtime values, operations on int values will overflow on 32 bits, and it is necessary to manually convert an int to a float to prevent such overflow.

For example:

```
var x : Int = 65536;
var y : Float = x;
y * y; // overflow, because we are multiplying two runtime int values

//instead, one should write:
var y : Float = x * 1.0; // convert int to float
```

**Comment by Simn** [comment]
Shouldn't the assignment of x to y come with an appropriate conversion?

**Comment by nadako** [comment]
that's what every other target that has different runtime types do

**Comment by ncannasse** [comment]
ATM we don't do this, I'm not sure we can find a way to detect each Int-to-Float conversions into genneko (passing Int as parameter to a function as well). Then there's Dynamic to Float too.

**Comment by Simn** [comment]
Yeah I'm just thinking we shouldn't document this as working-as-intended.

**Comment by Simn** [comment]
Meh neko
