### ISSUE TITLE
Code padding

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/HaxeManual#93]
Some examples have strange alignment in the online version:
http://haxe.org/manual/lf-pattern-matching-variable-capture.html

**Comment by ncannasse** [comment]
Up ! that makes examples quite hard to read
http://haxe.org/manual/macro-enum-building.html

**Comment by Simn** [comment]
sigh, I'll revert all the code example changes that I made so it looks good on kindle. I thought they looked okay in the PDF output but I agree the web version looks really bad.

**Comment by jasononeil** [comment]
Is this something that can be solved on the website markdown->html or css end?

I find the alignment in the [raw markdown](https://raw.githubusercontent.com/HaxeFoundation/HaxeManual/master/md/manual/macro-enum-building.md) confusing too so I think something in the generation will have to change.  But if you can see a way to make changes at the markdown->html level that will help let me know.

**Comment by Simn** [comment]
It's alright, I'll just have to think of something different for the e-book versions which nobody reads anyway.

**Comment by markknol** [comment]
This is mostly because we take [snapshots](https://github.com/HaxeFoundation/HaxeManual/blob/master/06-language-features.tex#L240) out of the code that is [part](https://github.com/HaxeFoundation/HaxeManual/blob/master/assets/PatternMatching.hx#L25-L32) of a complete class, right? Why not just put it in place?

**Comment by Simn** [comment]
No the code itself is wrapped in a weird way because I thought I could make it work for both e-book and online versions.

**Comment by markknol** [comment]
http://haxe.org/manual/types.html I found this one has still some weird alignment.

**Comment by Simn** [comment]
Yeah there might be some inline-code which I didn't change.
