### ISSUE TITLE
Macro Type not documented

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/HaxeManual#94]
I couldn't find the documentation for haxe.macro.MacroType in the Manual, maybe it should be added to the macro section ?

Also, there seems to be missing sections in "Limitations" ( 9.6.1 and 9.6.4 )

**Comment by nadako** [comment]
I think we should deprecate `MacroType` in favor of `@:genericBuild`.

**Comment by Simn** [comment]
That's why I didn't originally document it, but I _guess_ it's still sort of useful in case you want to define a single structure type which doesn't depend on anything but global state.

**Comment by Simn** [comment]
Maybe I'm wrong, for some reason I thought the macro would be executed several times, but that's obviously not the case. So this for example would work too:

```
@:genericBuild(MyMacro.getFields())
class BuildFields<Const> {}

typedef Fields = BuildFields<"file.txt">;
```

It also looks much nicer. :) So yes I'm in the deprecation camp as well.

**Comment by ncannasse** [comment]
Given that @:genericBuild is not documented either I can't decide on this :)
